[project]
name = "huggingface-deep-rl-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = []

[tool.setuptools.packages]
find = { include = ["unit2_hands_on"] }